// <auto-generated />
namespace EstoqueEntityModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PermiteEstoqueProdutoNulo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PermiteEstoqueProdutoNulo));
        
        string IMigrationMetadata.Id
        {
            get { return "201710141827239_Permite-EstoqueProduto-Nulo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
